### ISSUE TITLE
[BUG] - Nuxt-Quasar quietSassWarnings option is not working

### ISSUE THREAD

**Issue by YuZih** [Maiquu/nuxt-quasar#105]
### Environment

- Operating System: Darwin
- Node Version:     v22.12.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.15.0
- Builder:          -
- User Config:      default
- Runtime Modules:  nuxt-quasar-ui@2.1.7
- Build Modules:    -

### Quasar version

v2.17.5

### Browsers

Chromium

### Description

Despite I have set quietSassWarnings option to be true,  sass deprecation warnings are still being printed out.
```typescript
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
	modules: ['nuxt-quasar-ui'],
	vite: {
		css: {
			preprocessorOptions: {
				scss: {
					api: 'modern-compiler',
				},
			},
		},
	},
	quasar: {
		plugins: ['Dialog', 'Notify'],
		sassVariables: '~/assets/scss/_quasar.variables.scss',
		// sassVariables: true,
		quietSassWarnings: true,
	},
})

```
<img width="667" alt="截圖 2024-12-15 21 27 21" src="https://github.com/user-attachments/assets/545f8c83-f55b-44b5-bb41-df589e7777b3" />

And below is the setting of my  '_quasar.variables.scss' file: 
```scss
@use "quasar/src/css/variables" as q;
@use "sass:map";

/* Colors Variables Override & Custom */
// Set my own colors
$primary: #09e6ff;
$primary-01: #9dcbff;
$secondary: #7b00d9;
$secondary-01: #975abe;
$grayscale-01: #252424;
$grayscale-02: #7f7f7f;
$custom-colors: (
  primary: $primary,
  primary-01: $primary-01,
  secondary: $secondary,
  secondary-01: $secondary-01,
  grayscale-01: $grayscale-01,
  grayscale-02: $grayscale-02
);

@each $name, $color in $custom-colors {
  // Override Quasar colors
  .bg-#{$name} {
    background: $color;
  }
  .text-#{$name} {
    color: $color;
  }
}

```
I’m not sure if I did something wrong, but the problem of sass warnings have been bothering me. Can someone help me resolve it?

### Reproduction steps
Reproduction : [https://stackblitz.com/~/github.com/YuZih/quasar_test](https://stackblitz.com/~/github.com/YuZih/quasar_test)
```bash
1. run 'pnpm dev'
2. Go to 'http://localhost:3000/' on your browser
3. See log in terminal
```

### Logs

```bash
DEPRECATION WARNING: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api

DEPRECATION WARNING: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

"'~/assets/scss/_quasar.variables.scss'"
    node_modules/.pnpm/quasar@2.17.5/node_modules/quasar/dist/quasar.sass 10:9  root stylesheet

DEPRECATION WARNING: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

"'quasar/src/css/variables.sass'"
    node_modules/.pnpm/quasar@2.17.5/node_modules/quasar/dist/quasar.sass 11:9  root stylesheet
```
